name: training_sdf_network
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.12
  - numpy=1.21.2
  - pytorch=1.10.1
  - pykdtree=1.3.4
  - tensorboard=2.6.0

  - pip
  - pip:
      - tqdm==4.62.3
      - trimesh==3.9.35